name: TESTING

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      workflow_value: 
        description: "Are we 1337?"
        required: true
        default: "1337"
        type: choice
        options:
        - "1337"
        - "no 1337"

jobs:
  testjob:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: First
        run: |
          echo "We are working in the directory $GITHUB_WORKSPACE"
          echo "Exporting a variable to env: banana=tasty"
          echo "banana=tasty" >> "$GITHUB_ENV"
          echo "cache_key=cache-$( date +%Y_%m_%dT%H_%M_%S )" >> "$GITHUB_ENV"
          
      - name: Cache
        uses: actions/cache@v2.1.8
        with:
          path: the-cache
          key: ${{ env.cache_key }}
          restore-keys: cache-

      - name: Checking the cache
        run: |
          echo "Are bananas tasty? Previous script says:"
          echo $banana

          ls -lah the-cache || true
      
      - name: Filling cache
        run: |
          mkdir -p the-cache
          echo hello world > $( mktemp -p the-cache )
